### ISSUE TITLE
Feedback on Readme's "ACCESS-OM2 model output" section?

### ISSUE THREAD

**Issue by navidcy** [navidcy/IntrinsicOceanicLFVariabilityUOHC#1]
@aidanheerdegen, could you have a look at this repo's [README](https://github.com/navidcy/IntrinsicOceanicLFVariabilityUOHC/blob/master/README.md), in particular section "ACCESS-OM2 model output", and let me know if you feel I could have been clearer about accessing ACCESS-OM2 output from NCI?

**Comment by aidanheerdegen** [comment]
If you did want to point it out, one set of 0.1 degree IAF data is available via THREDDS

https://dapds00.nci.org.au/thredds/catalogs/cj50/access-om2/raw-output/access-om2-01/access-om2-01.html

Also NCI isn't the only Australian HPC centre. Maybe replace "Australia's HPC" with "the Australian National Computing Infrastructure (NCI)". Wouldn't hurt to link to it either.

Otherwise seems very comprehensive.

**Comment by navidcy** [comment]
Thanks!

What is THREDDS?

**Comment by aidanheerdegen** [comment]
https://www.unidata.ucar.edu/software/tds/current/
